spring:
  profiles:
# 집에서 사용할땐 home profile을 사용하고 노트북에서 사용할땐 notebook 프로파일을 사용한다
# 어떤 프로파일을 사용하는가에 따라 logback-spring.xml에 설정한 springProfile 태그에 설정된 로그 파일 저장 디렉토리를 이용해서 로그를 저장하게 된다
#    active: home
     active: notebook,h2_log4jdbc
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
